site_name: 重庆大学操作系统实验文档
copyright: 'Copyright &copy; 2022 College of Computer Science, Chongqing University.'
theme:
  name: material
  features:
    - navigation.tabs
nav:
  - 主页: index.md
  - 实验零-裸机程序:
    - 背景介绍: lab0/intro.md
    - 搭建实验环境: lab0/setup.md
    - 编写裸机程序: lab0/bare-prog.md
    - 实验任务: lab0/task.md
  - 实验一-异常与中断:
    - 获取实验资料: lab1/getcode.md
    - 背景介绍: lab1/intro.md
    - 代码讲解: lab1/code.md
    - 实验步骤: lab1/step.md
    - 实验任务: lab1/task.md
  - 实验二-内存管理:
    - 背景介绍: lab2/intro.md
    - 代码讲解: lab2/code.md
    - 实验步骤: lab2/step.md
    - 实验任务: lab2/task.md
  - 实验三-进程管理:
    - 背景介绍: lab3/intro.md
    - 实验目的: lab3/goal.md
    - 编译方法: lab3/method.md
    - 实验任务: lab3/task.md
  - 实验四-文件系统:
    - 背景介绍: lab4/intro.md
    - 实验目的: lab4/goals.md
    - 编译方法: lab4/compile.md
    - 实验任务: lab4/tasks.md
  - 开发板运行:
    - Nexys4DDR: chiplab/n4ddr.md
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true
markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
repo_name: 'osexp-docs-cqu'
repo_url: 'https://github.com/cyyself/osexp-docs-cqu'
